// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhjX4e4MBaCAtHfcifixWnsvdsPjxsxGA',
    appId: '1:517692301965:web:e838ec2528addb4e3978c4',
    messagingSenderId: '517692301965',
    projectId: 'flutter-chat-app-fbaa6',
    authDomain: 'flutter-chat-app-fbaa6.firebaseapp.com',
    storageBucket: 'flutter-chat-app-fbaa6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb7kpSWT8dDpvp3f4jmZzCAUGWHBdxuf0',
    appId: '1:517692301965:android:537b495434d9a6b93978c4',
    messagingSenderId: '517692301965',
    projectId: 'flutter-chat-app-fbaa6',
    storageBucket: 'flutter-chat-app-fbaa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATLxiDKLmKEG2zFeZGIki6L1JrStieAtQ',
    appId: '1:517692301965:ios:3ab7e62237ae6cde3978c4',
    messagingSenderId: '517692301965',
    projectId: 'flutter-chat-app-fbaa6',
    storageBucket: 'flutter-chat-app-fbaa6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATLxiDKLmKEG2zFeZGIki6L1JrStieAtQ',
    appId: '1:517692301965:ios:3ab7e62237ae6cde3978c4',
    messagingSenderId: '517692301965',
    projectId: 'flutter-chat-app-fbaa6',
    storageBucket: 'flutter-chat-app-fbaa6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhjX4e4MBaCAtHfcifixWnsvdsPjxsxGA',
    appId: '1:517692301965:web:da51f8f1ce02d9a23978c4',
    messagingSenderId: '517692301965',
    projectId: 'flutter-chat-app-fbaa6',
    authDomain: 'flutter-chat-app-fbaa6.firebaseapp.com',
    storageBucket: 'flutter-chat-app-fbaa6.appspot.com',
  );

}